---
title: "FA542 - Homework #4"
subtitle: "I pledge my honor that I have abided by the Stevens Honor System."
author: "Sid Bhatia"
date: "2023-11-16"
output: pdf_document
---

## Problem 1

Download daily price data for January 1, 1990 through November 1, 2023 of Microsoft stock from Yahoo Finance. You may use the quantmod package in R for this purpose.

```{r}
library(quantmod)

# Set the date range.
start_date <- as.Date("1990-01-01")
end_date <- as.Date("2023-11-01")

# Download the data.
getSymbols("MSFT", src = "yahoo", from = start_date, to = end_date)

# View the data.
head(MSFT)
```

#### a.

Is there any evidence of serial correlations in the monthly log returns. Use autocorrelations and 5% significance level to answer the question. If yes, remove the serial correlations.

#### b.

Is there any evidence of ARCH effects in the monthly log returns? Use the residual series if there are serial correlations in part (ii). Use Ljung-Box statistics for the squared returns (or residuals) with 6 and 12 lags of autocorrelations and 5% significance level to answer the question.

#### c.

Identify an ARCH model for the data and fit the identified model. Write down the fitted model and justify your choice of parameters.

## Problem 2

Use the following commands to simulate a two-regime $\text{TAR}(1)$ model with 400 observations

require(NTS)
set.seed(1)
phi <- matrix(c(0.8,-0.7),2,1)
m1 <- uTAR.sim(400, c(1,1), phi)
xt <- m1$series

#### a.

Obtain a time plot for the data and its sample autocorrelation function with 12 lags.

#### b.

Obtain a scatter plot for $x_t$ versus $x_{t-1}$ and draw a smooth line on the plot using loess local smoothing.

#### c.

Apply threshold tests to confirm the threshold nonlinearity of the time series.

#### d.

Build a two-regime TAR model for the series and write down the fitted model.

## Problem 3.

Consider the monthly mean duration unemployment in US. The data is seasonally adjusted from January 1948 to August 2017 and it is available in the file Unempduration.csv. The mean duration shows an upward trend so let $x_t$ be the first difference of the original data. 

#### a.

Build a linear $\text{AR}$ model for $x_t$. Write down the fitted model and perform model checking.

#### b.

Perform threshold tests to confirm that $x_t$ exhibits threshold nonlinearity.

#### c.

Use $p = 5$ and $d \in {1, \cdots, 5}$, where $d$ denotes the delay for selection of the threshold variable $x_{t-d}$. You may use the $p$ value of the threshold test to select $d$.

#### d.

Build a two-regime $\text{TAR}(5)$ model for $x_t$. Perform model checking and write down the fitted model.

#### e.

Compare the linear $\text{AR}$ model and the $\text{TAR}$ model.


## Problem 4.

Suppose that the monthly log returns, in percentages, of a stock follow the following Markov switching model:

$$
\begin{gathered}
r_t=1+a_t \quad a_t=\sigma_t \varepsilon_t \\
\sigma_t^2=\left\{\begin{array}{c}
0.1 a_{t-1}^2+0.8 \sigma_{t-1}^2 \quad \text { if } \quad S_t=1 \\
5+0.1 a_{t-1}^2+0.5 \sigma_{t-1}^2 \quad \text { if } \quad S_t=2
\end{array}\right.
\end{gathered}
$$

where the transition probabilities are:

$$\mathbb{P}(S_t = 2 \mid S_{t-1} = 1) = 0.1 \\
\mathbb{P}(S_t = 1 \mid S_{t-1} = 2) = 0.2$$

Suppose that $a_100 = 6, \sigma^2_{100} = 50,$ and $S_{100} = 2$ with probability $1$.

#### a.

What is the 1-step-ahead volatility forecast at the forecast origin $t = 100$?

#### b.

If the probability of $S_{100} = 2$ is reduced to $0.9$, what is the 1-step-ahead volatility forecast at the forecast origin $t_100$?